### ISSUE TITLE
Enable `fail-fast` to immediately fail the status checks on linter & formatting errors

### ISSUE THREAD

**Issue by Jarmos-san** [developersIndia/website#108]
## What's the Concern

The current CI environment runs good but not well enough. It doesn't fail on lint & formatting issues which means prospective contributors can sneakily pass through non-standard coding practices. While each PR are reviewed thoroughly but an automated process is necessary to be efficient.

Hence, the current workflow configurations available at [`.github/workflows/main.yml`](https://github.com/developersIndia/website/blob/master/.github/workflows/main.yml) should be refactored as required.

## Possible Solution

Enable the [`fail-fast` strategy](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) in the workflow so that when a single job (say the linter or formatter job) fails, the whole workflow should immediately exit. This will save us a lot of build minutes, make the CI/CD more efficient & robust.

## Resources for Reference

- [5x Speedup on CICD via Github Action's Strategy.Matrix](https://hanxiao.io/2021/01/24/Speedup-CI-Workflow-in-Github-Actions-via-Strategy-Matrix/)
- [How-to Github Actions: Build Matrix](https://ncorti.com/blog/howto-github-actions-build-matrix)
- [How to fail a job in Github Actions?](https://stackoverflow.com/questions/57903836/how-to-fail-a-job-in-github-actions)

**Comment by anubhav823** [comment]
Hi. I would like to contribute to this

**Comment by Jarmos-san** [comment]
@anubhav823 sure! Please share a proposal of a possible fix before you send a PR with us.

**Comment by anubhav823** [comment]
@Jarmos-san I was wondering if instead of failing the job for formatting issues, will it be better if we automate the formatting process?

**Comment by anubhav823** [comment]
@Jarmos-san I was thinking adding strategy: fail-fast: true to the job runCodeQualityChecks. Will that be okay?

**Comment by Jarmos-san** [comment]
@anubhav823 well in an ideal scenario that's the easiest way to go but check out #155 (the CI/CD pipeline is a stupid mess right now). I would like to focus more attention on that first because going forward it's probably going to need a major refactor.

**Comment by anubhav823** [comment]
@Jarmos-san should I give #155  a go? I am not familiar with this but I want to learn.

**Comment by Jarmos-san** [comment]
@anubhav823 sure! Please don't hesitate to reach out to me or @Bhupesh-V over Discord in case you figured out a way or two!
