### ISSUE TITLE
Setup tests for the project

### ISSUE THREAD

**Issue by Jarmos-san** [developersIndia/website#109]
## What's the Concern

The project doesn't have a single test written or configured yet! At it's current state the project is manageable & new features can be added without worrying about introducing some breaking changes. But once the project grows big enough, tests would be an absolute necessity by then.

So, it's good to get started writing & configuring the project with tests as quick as possible.

## Possible Solutions

The Next.js official documentations suggests the following four frameworks for testing:

- Cypress
- Playwright
- Jest + React Testing Library

...and it appears there's no clear "_one solution for everything_" when it comes to testing web app projects. So, if you've any ideas please share them over at #100.

cc @afkcodes if you've experience writing tests for frontend projects, could share some insights into how it's done?

**Comment by suryarajendhran** [comment]
If no one has picked this up, you can assign me to this, I'm happy to write some cypress tests to get started. And as for suggestions about how it's done. Here's a breakdown of how different types of tests can be employed:

1. **Unit testing:** Can be used on the backend and on frontend helpers. But for now, unless we start to have a complex backend, we should be fine without this for the moment. I can still set this up.
2. **Component testing:** This is a bit tedious and doesn't offer a huge return on time/effort investment. So best to avoid it unless there are specific usecases that require it. So we'd be fine pushing this to a later time.
3. **E2E testing:** This is perhaps the most important and easiest to start with. We use cypress and test the actual website on chrome. All frontend and backend changes should be E2E tested at the minimum.

As a sidenote, are there any CI/CD pipelines set up on Vercel or should we rely on github actions for that?

**Comment by Jarmos-san** [comment]
Hi @suryarajendhran thanks for taking the initiative but currently we don't have the resources to write & maintain test suites yet (hence it's left under the "[next](https://github.com/developersIndia/website/milestone/2)" milestone for now). The immediate & top most priority right now is to get a bare minimum static site deployed & have a robust CI/CD pipeline in place for the near future.

About the CI/CD pipeline, we're in the process of migrating away from Netlify to GitHub Actions. #137 did provide us with a template configuration to work with but for whatever reason it isn't working as expected. I've plans to investigate it further over the weekends & fix it soon because a contributor has already started working on developing the static site.

**Comment by suryarajendhran** [comment]
Alright then let me know if you need a hand with anything.
