### ISSUE TITLE
[BUG]: Builds fail on CI/CD

### ISSUE THREAD

**Issue by NiketanG** [developersIndia/website#126]
### What happened?

Tailwindcss was removed in favor of NextUI, [commit](https://github.com/developersIndia/website/commit/2e724c904908c689d58405a79f05536c079ffea7).

However, the imports are still present in [styles/globals.css](https://github.com/developersIndia/website/blob/master/src/styles/globals.css). 
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

Along with that, `postcss` and its [config](https://github.com/developersIndia/website/blob/master/postcss.config.js) and, [tailwindcss config](https://github.com/developersIndia/website/blob/master/tailwind.config.js) is still present, which again causes the issue.
```
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
```

Which causes the CI/CD builds to fail

### Relevant log output

```shell
Error: Cannot find module 'tailwindcss'

Import trace for requested module:
./src/styles/globals.css
./src/pages/_app.tsx
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jarmos-san** [comment]
Hi @NiketanG thanks for reporting the issue! Yes, we're in the middle of removing TailwindCSS in favour of NextUI (see #124). Moving forward we'll definitely be using NextUI for styling the website (I'm tired of changing the tech stack repeatedly & adding unnecessary complexity to the project).

So, if you would like please feel free to share a PR cleaning up any traces of TailwindCSS in the project. Don't forget to make documentation changes as well?
