### ISSUE TITLE
Issue tracker for the Footer section of the landing page

### ISSUE THREAD

**Issue by Jarmos-san** [developersIndia/website#136]
This thread tracks the enhancements, development & bug reports related to the CTA & Footer section of the landing page. Here's what they look like:

For more context on the overall project & what the landing page should look like, check out #133 

The CTA: 

![CTA](https://user-images.githubusercontent.com/31373860/156895348-118568ac-7b27-45d9-8863-b831fc5f1cb0.png)

The Footer:

![Footer](https://user-images.githubusercontent.com/31373860/156895353-91ae7447-77ef-430a-b6d5-3d2af5d858f6.png)

Use the comment section to keep a track on the progress of the development of this section.

**Comment by uragirii** [comment]
Hi, I wanted to claim this task 👋🏼. Let's have a call and catch up on design 🎨

**Comment by rohantejeswar** [comment]
@uragirii have you picked up this task? If not I can claim and work on this

**Comment by uragirii** [comment]
Yes, @rohantejeswar i have already picked these tasks. Although currently it’s paused until we fix pipeline problems

**Comment by Jarmos-san** [comment]
Hey y'all thanks for taking the initiative to contribute to the project! I simply wanted to let you all know, I'm working on fixing the CI/CD pipeline fixed! I've read the docs thoroughly & I believe I "kinda" know what's wrong with it. I'll still have to wait for Sunday because that's when Bhupesh is generally available & I need admin access to the org's settings as well.

Till then you guys can fork the project & experiment with the project!
