### ISSUE TITLE
[BUG]: `length` is declared here

### ISSUE THREAD

**Issue by Jarmos-san** [developersIndia/website#145]
### What happened?

TypeScript complains about an issue like the screenshot below:

![image](https://user-images.githubusercontent.com/31373860/159735685-6cf50f24-63a2-46b8-9277-f9180b0f4c01.png)

It could be caused by an [upstream issue](https://github.com/modulz/stitches/issues/947).

cc: @DevanshBajaj 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DevanshBajaj** [comment]
Would like to mention this as a possible [fix](https://github.com/modulz/stitches/issues/947#issuecomment-1061809383)

**Comment by Jarmos-san** [comment]
@DevanshBajaj can you confirm the issue is fixed now?

P.S: You might've to reclone the project & start afresh to check if the issue persists. For more context, I added a workspace configuration for VSCode to specifically use TypeScript v4.5.5! So, VSCode users won't have to face this issue ever again (hopefully). And they don't even have to resort to some manual hacks later on either.
