### ISSUE TITLE
[BLOCKER]: Broken CI/CD Pipeline

### ISSUE THREAD

**Issue by Jarmos-san** [developersIndia/website#155]
## What's the Issue

At the time of writing this thread, I've been attempting to battle this issue with our broken CI/CD pipeline's workflow. And so far it's been pretty much an uphill battle with GitHub's obscure documentations & unhelpful responses from GitHub's support team.

Regardless, here's what our ideal workflow would look like:

1. Interested contributed share their PRs which should trigger a suite of workflows (which are supposed to perform a variety of tasks like code quality checks & what not).
2. The first workflow to **ALWAYS** run is the "Code Quality Check" job which could include tasks like:
    -  Running the test suite & ensure all tests pass sucessfully.
    - Running ESLint, Prettier & other tools to ensure the source code adheres to a standard practice.
    - Other related tasks should be included here.
3. Once the "Code Quality Check" job passes successfully, it would trigger the workflow to run a "Build Website" job.
4. Upon the "Build Website" job's success, the workflow would then deploy to Netlify with a "[preview deployment URL](https://docs.netlify.com/site-deploys/deploy-previews/)".
5. If the deployment was successful, the workflow would comment on the PR with a link to the "preview deployment URL".

## Observations Made

So far, after multiple attempts at fixing the workflow, here are the following observations I made:

1. **GH doesn't allow access to the secret tokens to workflows triggered by PRs of forked repos**. :slightly_smiling_face: 
2. The [Netlify GH Action](https://github.com/nwtgck/netlify-action) we're using works as expected (as is evident through #150).
3. The documentation & the support team recommends using the `pull_request_target` event to trigger the workflow. The caveat while using this event is, the workflow will run in context to the base repo & not the contents of the PR. This means, the deployment URL willn't contain the changes as shared through the said PR (see #154).

## Resources to Understand GitHub Action's Functionality

- https://github.com/dependabot/dependabot-core/issues/3253
- [Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests)
- [GH Docs on Security](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#overview)
- [Make Secrets Available to Builds of Forks](https://github.community/t/make-secrets-available-to-builds-of-forks/16166)
- [How to use the GitHub Actions `workflow_run` event?](https://stackoverflow.com/questions/63343937/how-to-use-the-github-actions-workflow-run-event)
- [Events That Trigger Workflows - `workflow_run`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run).

## Possible Solutions to Fix the Issue

The only possible solutions I can think of on the top of my mind right now are:

1. Perform a complete refactor of the pipeline to adhere to GH's security concerns by following [this advice](https://github.community/t/how-do-i-allow-access-to-secret-tokens-to-workflows-triggered-by-prs-from-forks/245463/2?u=jarmos-san). Will it work? That remains to be experimented on, so contributions are welcome!
2. Use a mix of both Netlify's CI/CD pipeline & GH Action for the various tasks. For example, perform code quality checks, run the test suite & such on GH Action. While Netlify would take care of the CI/CD needs on each PR. This path has a drawback, as in Netlify's 300 limited build minutes will be over in mere weeks if not days!
3. If Netlify's limited build minutes isn't enough, then move to Vercel instead which offers a whooping 1000 build minutes (which is still nothing compared to GH's 2000 build minutes!).

## Why're We Desperate to Stick With Gh Actions?

Every interested contributor I had a chat with about this issue had one thing to say:

> Netlify takes care of X & Z, why bother using GH Action?

We use GH Action for one main simple reason which is to keep anything & everything related to CI/CD pipeline under a single roof. Other reasons include, Netlify's limited build minutes & inaccessible public logs in case something breaks during the build procedure.

## Ending Words

If it's not already evident, I'm tired & frustrated spending my weekends fighting an uphill battle with GitHub. So, if you've any ideas, possible fixes, alternatives or any magical solution to fix our CI/CD pipeline, I'm all ears!

Please don't hesitate to reach out to me over Discord (`Jarmos#8937`) or heck even use the comment section below to communicate. Any positive contributions to this problem we're facing would be **VERY** appreciated right now.

**Comment by HarshCasper** [comment]
Hi @Jarmos-san 👋 

I have raised a PR to fix this issue for you :) 

The PR preview workflows will now stick with GitHub Actions and use Surge instead of Netlify. You will need to configure a `SURGE_TOKEN` using the Surge CLI and add it as a GitHub secret with the name `SURGE_TOKEN`. The workflow has been used with various popular projects, like LocalStack and Devfiles and will hopefully work here as well!

Let me know if you have any questions or concerns!
