### ISSUE TITLE
Create a custom 404 page

### ISSUE THREAD

**Issue by Jarmos-san** [developersIndia/website#159]
### Describe the nature & the intricate details of the enhancement of your suggestions.

Currently the project doesn't have a custom 404 page & it serves the default one created by Next.js. While it works but having a custom 404 page will improve the brand value of the website & the community in general.

### Are you willing to take the initiative to implement & contribute a PR of the said feature/enhancement?

No

### Will this enhancement require a significant code refactor or an increase in the total numer of lines of code in the source code?

Yes

### Code of Conduct

- [X] I agree to follow the community's Code of Conduct

**Comment by Jarmos-san** [comment]
I'm assigning this task to @bhupeshpr25 since he agreed to take it up.

**Comment by bhupeshpr25** [comment]
thanks, I will take it up 👍
