### ISSUE TITLE
Develop a basic official developersIndia landing to start with

### ISSUE THREAD

**Issue by Jarmos-san** [developersIndia/website#20]
The [developersIndia](https://www.reddit.com/r/developersIndia "developersIndia | Reddit") community requires an official website. Members of the community did work on it on & off for a while but none of the contributions led to any productive goals yet. As such we had a long discussion & decided to take baby steps.

### The Plan Ahead

The immediate plan right now is to develop a **VERY** basic landing page with minimal aspects. In other words, features like dark mode or interactivity isn't a hard requirement right now. Developing an MVP which showcases our goals, who we're & how to be part of our community is all that's required for now. This is what we should be working towards for the "*first iteration*" of the project (more on it later on).

### The Tech Stack

We're working against the clock & since most of us are busy outside work hours as well, this project is maintained completely on volunteer basis & as "*a hobby project*". Hence, the tech stack is kept minimal with ample room for further additions if necessary.

That said, after a thorough discussion, following is the current tech stack to be used for developing a minimal landing page:

- [Next.js](https://nextjs.org "Next.js: The React Framework for Production") for building the frontend UI/UX.
- [TypeScript](https://www.typescriptlang.org "TypeScript is JavaScript with syntax for Types") for ease of maintenance & standard code quality assurance.
- [TailwindCSS](https://tailwindcss.com/ "Rapidly build modern websites without ever leaving your HTML.") \+ [SASS](https://sass-lang.com/ "CSS with superpowers") to build & style custom components.
- [Vercel](https://www.vercel.com "Develop. Preview. Ship") for deployment & hosting needs.

If you feel the project might benefit from using another tool or technology stack, please open an issue/discussion thread describing in details the benefits of it & some code samples of the implementation to go with.

### How Can You Contribute to the Project

Contributions to the project in **ANY** manner are **ALWAYS** appreciated. But if this is your first time contributing to FOSS projects, here are some ways we believe we could use your help:

1.  Got design skills and/or ideas? Please share your templates in this [discussion thread](https://github.com/developersIndia/developersIndia.in/discussions/6).
2.  Find something missing or perhaps a typo here & there? Feel free to let us know about it or even better, report it through an issue thread & then reference it on a PR!
3.  Keep an eye out on the discussions going in various issue/discussion threads & chime in with your opinion & suggestions. In our community we're always favor member engagement over everything else. And it also brings us joy to see we could provide a meaningful platform for individuals to help one another out.

Please don't assume the points above are the only ways you can contribute to the project! If you need, feel free to reach out to us over DMs & we'll be happy to discuss the other ways you might want to contribute to out community efforts.

### Ending Notes & Credits

Do note, we already have [an amazing Figma template](https://www.figma.com/file/jxpIq8GzilqzgyLpFBySP2/Developers-India-%3C3?node-id=0%3A1) to use as a source of inspiration to develop the "*first iteration*" of the website. And by *"first iteration"*, we mean the `v1.x.x` release of the project which you can track on the [releases page](https://github.com/developersIndia/website/releases).

This current issue thread will remain open for discussion & progress tracking until the `v1.x.x` is launched. After that the thread will be closed & locked for obvious reasons. As such if you would like share your ideas & templates for the minimal landing page of the website, please [share it](https://github.com/developersIndia/developersIndia.in/discussions/6) before the first public release of the website.

That said, we would like to thank @OmkarK45 & @sushilburagute for their contributions on designing the template we're using as a source of inspiration! Without their effort & contribution I doubt the project would've progressed as much as it did right now.

**Comment by sangeet** [comment]
Hi, I am happy to start converting Figma design to UI if nobody has taken it up yet.

**Comment by Jarmos-san** [comment]
@sangeet thanks for taking the initiative! :heart: 

Please feel free to go through the issue threads & reference PRs to them accordingly. Also don't forget to read the "[contribution guidelines](https://github.com/developersIndia/website/blob/master/.github/CONTRIBUTING.md)" before making a PR.

As for the template, you can take a look at it over here - https://www.figma.com/file/jxpIq8GzilqzgyLpFBySP2/Developers-India-%3C3?node-id=0%3A1

**Comment by SamrendraS** [comment]
I was working on the website but it fizzled out after too many people were unavailable. I've gone through the design and I really like it, and would like to start working on the website this weekend. I'm experienced with the tech stack so I'll be comfortable with kicking off.

Is there a Trello board or some ticketing system that I can come up to speed with; I'm going through the raised issues meanwhile

**Comment by Jarmos-san** [comment]
@SamrendraS thanks for taking the initiative! :heart: 

We're not tracking progress through kanban boards yet because the goals are quite small for now. Our immediate goals like right now is to:

1. Setup ESLint & Prettier, see #27 
2. Configure `lint-staged` + `husky` pre-commit hooks, see #40 (there's a WIP PR though)
3. Setup a bare minimum CI/CD pipeline which can be extended later on as needed, see #41 

The next steps would be to set up the Vercel account for hosting & deployment. We wanted to work on it but quite a lot of things happened (as you're already aware), the domain expired & we need to repurchase it. Doing all of that will probably take some internal collaborations from our end so we're hopeful the community will understand & be patient with us as well.

As for project fizzling out, yes, we're guilty of it because some of us got new jobs, were moving cities (thanks to Covid) among other personal obligations. We're back on track & will hopeful be able to ship the first iteration of the website soon enough!.

If you would like to fast track the development procedure we can have a quick chat over Discord or Google Meet (if you're comfortable).

**Comment by SamrendraS** [comment]
Thanks for the reply @Jarmos-san; Discord works for me; ree#4239.
I look forward to helping build the website :)

**Comment by siddhantk232** [comment]
I can help implement the landing page if nobody is working on it. For those who are working currently working on it, it would help if they could open a draft PR so that we can easily track what's going on. Thank you!

**Comment by NiketanG** [comment]
Would love to help as well. A board for tracking progress would be helpful

**Comment by Jarmos-san** [comment]
> Would love to help as well. A board for tracking progress would be helpful

@NiketanG yeah we've plans but we're not sure how should proceed ahead with sharing a project roadmap. If you've ideas, please feel free to share it us on [this discussion thread](https://github.com/developersIndia/website/discussions/69).

**Comment by afkcodes** [comment]
Will take it up if it's not started.

**Comment by afkcodes** [comment]
@Jarmos-san @Bhupesh-V @Manav-SM Let's kickstart this.

**Comment by Jarmos-san** [comment]
@afkcodes yes please! We were waiting for @varshney-himanshu to lead the development procedure but he has to take care of some urgent personal emergencies right now. It did cause us some delay but hopefully we can get started right away.

Any way, I assume you're the most experienced frontend dev so why don't you take the lead for the development process? And the rest of us will help you with maintenance & managing contributions to the project?

On that note, I'm working on a release cadence as I write this comment! It should detail out smaller achievable goals to help us break down the landing page template into smaller components. So, please look forward to checking it out.

**Comment by afkcodes** [comment]
okay, then I will plan this tomorrow.
