### ISSUE TITLE
Add ESLint & Prettier support to keep a check on development standard practices.

### ISSUE THREAD

**Issue by Jarmos-san** [developersIndia/website#27]
The general public has general opinion on the best development practices all the time. Some prefers using double quotes over single quotes, while others prefer semi-colons after a line & others don't. Debates on such meaningless topics are unproductive, as such having a proper [ESLint](https://eslint.org) & [Prettier](https://prettier.io) configuration in place should keep a check on a standard development practice.

For reference on how to setup the configurations for each of those dependencies, refer to ["Configuring ESLint"](https://eslint.org/docs/user-guide/configuring/) & ["Prettier Configuration Options"](https://prettier.io/docs/en/options.html)

**Comment by afkcodes** [comment]
i will take this up.

**Comment by Jarmos-san** [comment]
@afkcodes thanks for taking the initiative! ❤️  Feel free to open a PR referencing this issue.

P.S: Please keep in mind we'll be implementing pre-commit hooks with [Husky](https://typicode.github.io/husky/#/) & [lint-staged](https://github.com/okonet/lint-staged) as well at some point in time. And you should refer to the [Next.js docs for configuring ESLint](https://nextjs.org/docs/basic-features/eslint) since the React framework already provides some default settings.

**Comment by afkcodes** [comment]
Yeah, thanks will make a PR today or by tomorrow. Don't know i didn't get the above notification.

**Comment by Jarmos-san** [comment]
@afkcodes are you still interested in pursuing this issue? If so, please let us know by referencing this issue in a PR.

**Comment by NiketanG** [comment]
Is this being worked on ? 
If not, would love to work.
Thanks

**Comment by Jarmos-san** [comment]
@NiketanG PRs are welcome! If you do take it, then please reference this issue to close it automatically.

**Comment by afkcodes** [comment]
sorry really caught up with office work. couldn't make a PR, though i have made the changes now.

**Comment by afkcodes** [comment]
will be updating this by eod. the design looks cool and we can kickoff then.

**Comment by afkcodes** [comment]
I have raised a PR: Add eslint & prettier #62 here but seems like CI is missing peer-deps config. have less idea about it so do have a look.
