### ISSUE TITLE
Add pre-commit hooks for better code quality control

### ISSUE THREAD

**Issue by Jarmos-san** [developersIndia/website#40]
### Feature details?

[Git hooks](https://git-scm.com/docs/githooks) using frameworks like [husky](https://typicode.github.io/husky/#/) + [lint-staged](https://github.com/okonet/lint-staged) or [pre-commit](https://pre-commit.com/) will ensure bad coding standards & practices aren't introduced to the source code. They'll cleaned & taken care of right at the source.

Further quality control can be ensured by implementing an automated CI/CD pipeline but for starters, Git hooks is the way to go.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tarunkishore2303** [comment]
I have added the things you've mentioned. Can I push it ?
