### ISSUE TITLE
[BUG]: Giving credits to the non-source code contributors

### ISSUE THREAD

**Issue by Jarmos-san** [developersIndia/website#51]
### What happened?

[All Contributors](https://allcontributors.org/) might've missed out the following people:

| Credited? |                   GitHub Profiles                                          |          Their Contributions                  |
|:-------------:|-----------------------------------------------------------------------|-------------------------------------------------|
| :heavy_check_mark: |  [Omkar Kulkarni](https://github.com/OmkarK45)         | Co-designed the [website template](https://www.figma.com/file/jxpIq8GzilqzgyLpFBySP2/Developers-India-%3C3?node-id=0%3A1)   |
| :heavy_check_mark: |  [Sushil Buragute](https://github.com/sushilburagute)  | Co-designed the [website template](https://www.figma.com/file/jxpIq8GzilqzgyLpFBySP2/Developers-India-%3C3?node-id=0%3A1)   |
| :x: | [Bhupesh Varshney](https://github.com/Bhupesh-V)  | Co-maintainer of community & all community projects   |
| :x: | [Himanshu Varshney](https://github.com/varshney-himanshu)  | Co-maintainer of community & all community projects   |

Is it possible to add these people to the list of contributors as well?

Also let's keep this issue thread open till we release the first iteration of the website. We can use it to track people whose credits are due.

cc @Bhupesh-V 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bhupesh-V** [comment]
@all-contributors please add @OmkarK45 for content, design

**Comment by Bhupesh-V** [comment]
@all-contributors please add @sushilburagute for content, design

**Comment by Bhupesh-V** [comment]
@all-contributors please add @SamrendraS for code

**Comment by Jarmos-san** [comment]
@all-contributors please add @Bhupesh-V for code, infra, doc, tool, ideas, review

**Comment by Jarmos-san** [comment]
@all-contributors please add @varshney-himanshu for code, infra, doc, tool, ideas, review

**Comment by Jarmos-san** [comment]
Closing it in favour of #83 to reduce clutter & spam.

**Comment by Jarmos-san** [comment]
@all-contributors please add @siddhantk232 for review, doc

**Comment by Jarmos-san** [comment]
@all-contributors please add @afkcodes for review
