### ISSUE TITLE
[BUG]: ESLint in the CI/CD pipeline is broken

### ISSUE THREAD

**Issue by Jarmos-san** [developersIndia/website#65]
### What happened?

#62 configured & added ESLint & Prettier support to the project but it also broke the CI/CD pipeline for some reason. Need to fix it somehow, see the [failed workflows](https://github.com/developersIndia/website/actions/workflows/main.yml?query=is%3Afailure) for reference.

### Relevant log output

```
> website@0.1.0 lint /home/runner/work/website/website
> next lint

Failed to load config "next/core-web-vitals" to extend from.
Referenced from: /home/runner/work/website/website/.eslintrc.json
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! website@0.1.0 lint: `next lint`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the website@0.1.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-02-06T15_09_39_051Z-debug.log
Error: Process completed with exit code 1.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by afkcodes** [comment]
This is related to peer dependencies i guess. According to the the issue i was looking at yesterday.

**Comment by siddhantk232** [comment]
have a look at #66

**Comment by Jarmos-san** [comment]
> This is related to peer dependencies i guess. According to the the issue i was looking at yesterday.

Yup, you were right! Apparently, the `eslint-config-prettier` dependency were missing (lmao)! Thanks to @siddhantk232 who figured it out almost instantly & shared a PR right away as well :heart:.
