### ISSUE TITLE
[BUG]: `npm run build` fails due to a Type Error

### ISSUE THREAD

**Issue by PushpenderSaini0** [developersIndia/website#73]
### What happened?

When trying to build a `production build` with the command `npm run build` on my system
it fails with the error 
> Type error: Option 'emitDecoratorMetadata' cannot be specified without specifying option 'experimentalDecorators'.

[ScreenShot]
![image](https://user-images.githubusercontent.com/54404738/152909312-cd7535a3-ba4d-484d-a120-9007233181e8.png)

Possible fix that i found
-  Adding the option ` "experimentalDecorators":true ` in tsconfig.json fixes this issue

After above fix
[ScreenShot] 
![image](https://user-images.githubusercontent.com/54404738/152910172-8b6e0a53-c59e-4f58-889e-0bdbb92f728b.png)

You can assign me this issue and i will send a PR with the fix

My System
npm [8.4.1]
node [v17.3.0]

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by afkcodes** [comment]
the tsconfig file needs to be refactored, I guess.

**Comment by Jarmos-san** [comment]
Yes, as @afkcodes mentioned, the `tsconfig.json` file requires a slight bit more attention. I'll do that over the weekends (no promises though).

And about adding "experimental support", @PushpenderSaini0 hold up a bit, let me read up on what is this feature all about & I'll definitely assign this issue to you.

For those who're not well aware about "decorators", you can start reading about it from it's [`tsconfig.json` reference doc](https://www.typescriptlang.org/tsconfig#experimentalDecorators).

**Comment by Jarmos-san** [comment]
@PushpenderSaini0 can you take a look at #75 & share a PR referencing it instead? Once you prepare the PR, I'll close this issue in favour of that issue thread.

**Comment by Jarmos-san** [comment]
Closing it in favour of #75 & labelled it as a `duplicate`.
