### ISSUE TITLE
[FEATURE REQUEST]: Simplify `tsconfig.json` to make room for incremental changes when necessary

### ISSUE THREAD

**Issue by Jarmos-san** [developersIndia/website#75]
### Feature details?

The current state of the `tsconfig.json` is too "_strict_" & it should be "_toned down_" to make room for future increments. On top of it, simplifying the config file will also get rid of errors caused by experimental features like #73.

That said, Next.js already provides a standard default config file with the following contents:

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "esnext",
    "jsx": "preserve",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "noEmit": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true
  },
  "exclude": ["node_modules"],
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"]
}
```
The standard configurations should be a good starting point right now. Additionally, do take a look at the following config values which I think might benefit contributors with a better dev experience;

- [`baseUrl`](https://www.typescriptlang.org/tsconfig#baseUrl)
- [`paths`](https://www.typescriptlang.org/tsconfig#paths)
- [`noUnusedLocals`](https://www.typescriptlang.org/tsconfig#noUnusedLocals)
- [`noUnusedParameters`](https://www.typescriptlang.org/tsconfig#noUnusedParameters)

Add more of such config values I might've missed out & please have a productive discussion below before suggesting any additional config values.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by afkcodes** [comment]
Also, add path aliases. whoever is working on it.

**Comment by Jarmos-san** [comment]
For those who're wondering how to add path aliases:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    }
  }
}
```

**Comment by vigneshwar221B** [comment]
How about also adding some strict type checking options?

```json
{
  "compilerOptions": {
    "strict": true,                           
    "noImplicitAny": true,                    
    "strictNullChecks": true,                 
    "strictFunctionTypes": true,             
    "strictPropertyInitialization": true,     
    "alwaysStrict": true
  }     
}
```

**Comment by vigneshwar221B** [comment]
> Also, add path aliases. whoever is working on it.

Can you explain more on how the project structure is gonna be? Right now, I guess we can add one path alias for static media files and 1 path alias for a generic component folder. I don't know what else can we add?

```json
{
  "compilerOptions": {
      "paths": {
      "@static/*": ["public/*"],
      "@components/*": ["src/components/*"]
      },    
   }
}
```

**Comment by vigneshwar221B** [comment]
As, we are still discussing on whether to add the experimental options or not, I commented it out for now. Does this look good?

```js
{
  "compilerOptions": {

    // Basic Options 
    "target": "es2017",
    "lib": [
      "dom",
      "dom.iterable",
      "es6",
      "esnext",
      "es2017"
    ],
    "allowJs": true,                          
    "jsx": "react",                          
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,                

    // Strict Type-Checking Options 
    "strict": true,                           
    "noImplicitAny": true,                    
    "strictNullChecks": true,                 
    "strictFunctionTypes": true,             
    "strictPropertyInitialization": true,     
    "alwaysStrict": true,                     

    // Module Resolution Options
    "moduleResolution": "node",               
    "baseUrl": ".",                           
    "paths": {
      "@static/*": ["public/*"],
      "@components/*": ["src/components/*"]
    },                           
    
    // Experimental Options 
    // "experimentalDecorators": true,       
    // "emitDecoratorMetadata": true,         
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}

```

**Comment by Jarmos-san** [comment]
@vigneshwar221B cool looks good, would you like to work on a PR with the changes? But could you hold up for just a bit? I would like discuss something about support for experimental features & path aliases. Also do take a look at #80 which will refactor the current `tsconfig.json` to tone down on the strictness.

**Comment by vigneshwar221B** [comment]
Sure, get back to me when you finalise your decision on experimental features and path aliases. I'll make a PR.

**Comment by Jarmos-san** [comment]
@vigneshwar221B you can go ahead & share the PR with the changes you want to make on the current `tsconfig.json` file. Do note, some of the configurations have already been added in #80.

As for experimental support, let's hold on to them for now & we can add them when absolutely necessary later on.
