### ISSUE TITLE
Develop a `ROADMAP.md` for the project

### ISSUE THREAD

**Issue by Jarmos-san** [developersIndia/website#81]
### Feature details?

The project requires a public roadmap for better collaboration efforts. Having one such publicly facing documentation will help reduce redundant questions like the ones below from interested contributors:

1. _"Can I implement so & so feature to the website?!"_
2. _"What's the plan? I can help, what should I contribute to?"_
3. _"I've an amazing which is to add blah blah feature to the website! Can I add it to the website?"_
4. _"The website isn't up yet! What's taking so long?! I could've completed working on it in mere # of days! Tell me what can I help you with?"_

The list of such redundant questions are endless.

Having a public `ROADMAP.md` will help answer those redundant questions every now & then. On top of that, it'll also help interested contributors stay updated with:
- What feature requests are accepted.
- If there're any specific messages and/or events planned by the admin.
- Have better foresight on the project's development & act accordingly without any distractions.

That said, if you would like to share your ideas & suggestions on how this project's roadmap should be like, then please check out the comments section of #69.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bhupesh-V** [comment]
Testing webook, this shit works?
