### ISSUE TITLE
[FEATURE REQUEST]: Create a mobile-friendly template for the website

### ISSUE THREAD

**Issue by Jarmos-san** [developersIndia/website#90]
### Feature details?

Thanks to the generous contributions of the two selfless contributors, we had a template to base the design of the website to work on! Unfortunately, due to lack of time, they couldn't design the mobile-friendly version of the template. As such, if you guys have design skills, please reach out to us or comment down below on how you would like to proceed.

For reference, please take a look at the template over here: https://www.figma.com/file/jxpIq8GzilqzgyLpFBySP2/Developers-India-%3C3?node-id=5%3A58734

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jarmos-san** [comment]
@afkcodes would you like to design the mobile-friendly version of the website? Or do have some other ideas in mind, do let me know?

**Comment by afkcodes** [comment]
I really have no sense of design, to be honest, and don't want to ruin the mobile experience. we need someone who can take the desktop website make it look good on mobile as well. what happened to the folks who designed the desktop version of it.

**Comment by Jarmos-san** [comment]
Yup, same here lol designing isn't my cup of tea either! @OmkarK45 & one his friend designed the OG template shared above but it appears he got busy with his internship (**he's the only software dev in his company right now** :grimacing: )

**Comment by afkcodes** [comment]
yeah,  let's focus on the desktop first and whatever we can we will try to make it responsive and see how things pan out.
